### ISSUE TITLE
NATS EventStore spike

### ISSUE THREAD

**Issue by jeffmccune** [holos-run/holos#119]
Spike Event Sourcing + CQRS in Nats

 - https://github.com/bruth/rita
 - https://github.com/nats-io/nats-server/discussions/3772
 - https://github.com/bruth/kmm

Depends on:

 - [x] #120 
 - [x] #121

**Comment by sysradium** [comment]
I've had a similar spike. So far the only viable solutions are either something like PostgreSQL (not ideal) and EventStoreDB. 🤔
