### ISSUE TITLE
Tutorial does not render

### ISSUE THREAD

**Issue by mcfearsome** [holos-run/holos#335]
Following along https://holos.run/docs/v1alpha5/tutorial/hello-holos/ I go to run `holos render platform...` and am greeted with:

```
holos render platform ./platform --log-level debug
finalized config from flags
cue: discriminating platform instance
discriminated v1alpha5 Platform
render component
running: holos
could not run: could not run helm template: Error: chart requires kubeVersion: >=1.23.0-0 which is incompatible with Kubernetes v1.20.0: exit status 1 at builder/v1alpha5/builder.go:354
could not run: could not render component: exit status 1 at builder/v1alpha5/builder.go:136
```

**Comment by jeffmccune** [comment]
Thanks for reporting this @mcfearsome, taking a look at this.

**Comment by natemccurdy** [comment]
Hi @mcfearsome thanks for reporting this. As a temporary workaround, try setting the `KUBECONFIG` env var to `/dev/null` while running the `holos render platform` command. That should stop Helm from accessing the k8s API server, so it skips the compatibility check.

```
KUBECONFIG=/dev/null holos render platform ./platform
```

We're all at Kubecon this week, so hopefully this temporary fix works for you until we can find a permanent solution.

**Comment by mcfearsome** [comment]
```
KUBECONFIG=/dev/null holos render platform ./platform
could not run: could not run helm template: Error: chart requires kubeVersion: >=1.23.0-0 which is incompatible with Kubernetes v1.20.0: exit status 1 at builder/v1alpha5/builder.go:354
could not run: could not render component: exit status 1 at builder/v1alpha5/builder.go:136
```

I'm not even sure where it is getting v1.20.0 from
```
kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.8-eks-a737599
```

**Comment by jeffmccune** [comment]
@mcfearsome What helm version are you on?

I'll try and reproduce with your version, mine is:

```
❯ helm version
version.BuildInfo{Version:"v3.16.2", GitCommit:"13654a52f7c70a143b1dd51416d633e1071faffb", GitTreeState:"dirty", GoVersion:"go1.23.2"}
```

**Comment by jeffmccune** [comment]
According to https://github.com/helm/helm/issues/10760#issuecomment-1065225097

> helm template does not reach out to a Kubernetes cluster. It uses whatever APIVersions the Kubernetes client provides unless you pass the --validate flag.

> By Kubernetes client , you mean the one compiled?

> Yes

So I take this to mean the api version comes from the client compiled into the `helm` executable.  Please let us know the version, it'll help us figure out how best to address this.

**Comment by mcfearsome** [comment]
```
helm version
version.BuildInfo{Version:"v3.13.3", GitCommit:"v3.13.3", GitTreeState:"", GoVersion:"go1.21.5"}
```

**Comment by mcfearsome** [comment]
Updating Helm works...

```
nix-shell -p kubernetes-helm

helm version
version.BuildInfo{Version:"v3.15.2", GitCommit:"v3.15.2", GitTreeState:"", GoVersion:"go1.22.3"}

holos render platform ./platform
rendered podinfo in 180.910875ms
rendered platform in 181.22725ms
```

Might be good for an honorable mention in the documentation

**Comment by jeffmccune** [comment]
@mcfearsome Mentioned this [here](https://jeff-335-tutorial-does.holos.pages.dev/docs/v1alpha5/tutorial/setup/#dependencies) in the setup docs.  We'll make this more prominent with an important or warning admonition if someone else runs into this again.
